title: "Aurora MySQL v1 → v3（3.01.0 移行計画編）"
summary: "Amazon Aurora MySQL v1（5.6 互換）→ v3（8.0 互換）の移行を計画するための本です。バージョン間の変更点や移行の注意点などをまとめました。"
topics: ["aws", "aurora", "mysql", "移行", "バージョンアップ"] # トピック（5つまで）
published: true # falseだと下書き
price: 0 # 有料の場合200〜5000
chapters:
  - 01-top
  - 02-new-features
  - 03-pre-plan
  - 04-references
  - 05-research-01
  - 06-research-02
  - 07-research-03
  - 08-application
  - 09-check
  - 10-bottom